# Generated by Django 5.2 on 2025-04-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="producto",
        ),
    ]
