# Generated by Django 5.2 on 2025-04-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Completado", "Completado"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
