# Generated by Django 5.2 on 2025-04-14 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_pedido_estado_pedido_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.proveedor",
            ),
        ),
    ]
