# Generated by Django 5.2 on 2025-04-15 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_producto_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.pedido"
            ),
        ),
    ]
