# Generated by Django 5.2 on 2025-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_factura_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Completado", "Completado"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pedido",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
