# Generated by Django 5.2 on 2025-04-15 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_compra_cantidad_compra_estado_compra_precio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="productos",
        ),
        migrations.AddField(
            model_name="compra",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.producto",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="cantidad",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="compra",
            name="estado",
            field=models.CharField(
                choices=[("Pendiente", "Pendiente"), ("Completada", "Completada")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
