# Generated by Django 5.2 on 2025-04-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_compra_productos_compra_producto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="precio",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="productos",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="total",
        ),
        migrations.AlterField(
            model_name="compra",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.producto"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[("Pendiente", "Pendiente"), ("Completado", "Completado")],
                max_length=20,
            ),
        ),
    ]
