# Generated by Django 5.2 on 2025-04-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_compra_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compraproducto",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.producto",
            ),
        ),
    ]
