# Generated by Django 5.2 on 2025-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_pedidoproducto_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
