# Generated by Django 5.2 on 2025-04-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_pedido_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.producto",
            ),
        ),
    ]
