# Generated by Django 5.2 on 2025-04-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interno", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="producto",
        ),
    ]
